### ISSUE TITLE
-noworkshopmods download system

### ISSUE THREAD

**Issue by lorenrosenhal** [RF-Stuff/Bugs-Suggestions#109]
When using -noworkshopmods, you should be able to download mods and keep them in that one game (I mean until you restart the whole thing). This is possible with custom maps, but if I try to download a weapon or a vehicle it won’t appear. This could be really useful for people who like to play the game without it being made up of 95% memes and have too many mods to disable them 1-by-1.

**Comment by Modelmat** [comment]
This seems invalid. The entire point of `-noworkshopmods` is not to get any mods.
