### ISSUE TITLE
Having 2 rocket launchers (bug)

### ISSUE THREAD

**Issue by lorenrosenhal** [RF-Stuff/Bugs-Suggestions#113]
Whenever I use a rocket launcher (like the dagger), I always have 2 of them, while there only needs to be one. Talking about the beta branch

**Comment by Modelmat** [comment]
What do you mean 2 of them? You should only be able to have one.

**Comment by lorenrosenhal** [comment]
This is the bug. For some reason, I have 2 rocket launchers at once instead of only one! And no, they can’t be the same one since if I make once of them run out of ammo, the other one wouldn’t lose any. 
(No mods used)
