### ISSUE TITLE
Transport Helicopter

### ISSUE THREAD

**Issue by Artecus** [RF-Stuff/Bugs-Suggestions#145]
**Requirements**:
- [x] I have checked the repository for previous issues of this type
- [x] I have included a detailed description
- [x] This is one issue, not multiple issues

This helicopter would be akin to the bomber; a new interesting addition to the aerial arsenal to spice things up. It would be modeled after a Huey, making it more delicate to bullets and anti-air systems. This delicacy is balanced out by the fact that it is able to fire incendiary Area of Effect bombs and carry up to 6 team members, making it one of the most effective vehicles in the game (like the bomber). It should have 2 seats in the cockpit, one for an anti-air gun that will *not* fire on ground troops (AP .50 cal), and one for the pilot, who fires the incendiary bombs. The other seats are there so you can capture points easily with this helicopter after a calculated assault, much like the default Jeep, which is currently best for rushing a crippled point.

Overall, I think this helicopter would be a very fun addition to the skies, and would make for a much more interesting game, perhaps even more so than the bomber did, if balanced correctly.

**Comment by Modelmat** [comment]
This can be already done by the steam workshop, there is no need for this to exist as a default.
