### ISSUE TITLE
Combat Knife

### ISSUE THREAD

**Issue by Artecus** [RF-Stuff/Bugs-Suggestions#146]
**Requirements**:
- [x] I have checked the repository for previous issues of this type
- [x] I have included a detailed description
- [x] This is one issue, not multiple issues

A new melee weapon with new animations and special functionality.
If the knife is to be added, the wrench must be nerfed to do 25-35 damage instead of 100, for balance reasons.

The knife will kill instantly from behind and do 50 damage in the front. This positional damage would be difficult, but I think worth it to make the weapon more interesting.

The knife can be thrown with right-click, but you only have one, and you cannot get it back if it killed an enemy.

Instead of taking up an equipment slot, perhaps the knife could be in the secondary slot, if it is made to be primarily throwable.

In the end, the knife would breathe inspiration for new melee opportunities in the game, creating more interesting loadouts and special playstyles.

**Comment by Modelmat** [comment]
There is already the sabre, this seems very close to that and able to be modded - even if it is made as a gun.
