### ISSUE TITLE
Weapon Variants Menu (modded weapons)

### ISSUE THREAD

**Issue by Artecus** [RF-Stuff/Bugs-Suggestions#152]
**Requirements**:
- [x] I have checked the repository for previous issues of this type
- [x] I have included a detailed description
- [x] This is one issue, not multiple issues

"This is the 'Variants' menu."
"When opened, you see up to 3 variants."
"There is a slider, for many variants."
"The variants are easy to categorize and name in Unity."
![ravenfield variants menu](https://user-images.githubusercontent.com/37642308/39424430-b31b797e-4c44-11e8-8bc7-b71e3fc118a1.png)

**Comment by Modelmat** [comment]
See #153
