### ISSUE TITLE
Suggestion(s)

### ISSUE THREAD

**Issue by HighOnSteam** [RF-Stuff/Bugs-Suggestions#173]
**Requirements**:
- [x] I have checked the repository for previous issues of this type
(totally)
- [x] I have included a detailed description
(yes)
- [x] This is one issue, not multiple issues
(i don't want to have to make multiple so deal with it)

Select Fire ability (Single, Burst, Auto)

Have interactive doors so map makers can create buildings with interiors

Variable Scope Zoom Ablity

A handbrake for vehicles

Make vehicles not take damage when falling short distances if they land on their wheels

**Comment by Modelmat** [comment]
Those requirements must be validated.
Ignoring them does make this issue invalid.
