### ISSUE TITLE
Permanently or conditionally locked flags.

### ISSUE THREAD

**Issue by BramKaandorp** [RF-Stuff/Bugs-Suggestions#91]
It would be cool to have the ability for certain flags to be locked (permanently owned by one team), or only capturable if one or more other specified flags are captured.

It would make a predetermined capturing order possible.

Forgotten Hope 2 had this perfected, and I'd love to play maps which use this type of gameplay.

It would also allow for maps with Conquest: Assault Lines type gameplay like in BF2142.

**Comment by Modelmat** [comment]
#75

**Comment by BramKaandorp** [comment]
I don't see how this suggestion and #75 are related.

**Comment by Modelmat** [comment]
Oh. wrong one...
