### ISSUE TITLE
Landable Planes

### ISSUE THREAD

**Issue by Modelmat** [RF-Stuff/Bugs-Suggestions#93]
Planes that can land, place gear out, slow down, etc.
I've already made a mod for this, it's not that hard.

**Comment by rodeje25** [comment]
you can do this by setting it up in the animator controller

**Comment by Modelmat** [comment]
Is this available  in default planes? And how is this so? Any custom key binds, etc? Pending reopening

**Comment by rodeje25** [comment]
not available in default planes *yet*
but modders can do this and steel can set this up as well
