### ISSUE TITLE
Parachutes and a chest slot - what are the possibilities? Will this be better as an alternative to ladders?

### ISSUE THREAD

**Issue by Maffnwy** [RF-Stuff/Bugs-Suggestions#97]
#suggestion 
 I just wanted to give you some recognition for your latest update. Well done, my friend - I find the enemies to be not just more challenging, but less predictable and more interesting - a feeling I dare say a lot of modern games lack. Overcoming them Is truly rewarding, and working alongside them even without giving them orders - letting them lead (according to a clear plan as marked on the map), and playing alongside their improved pre/post-engagement tactics. THANK YOU! Also, congratulations on the new map... my only question for you, as somebody who develops as well, is this:
Are the ladders going to be at all useful; will players just get shot off them immediately by AI?
People seem well adjusted to jumping out of aircraft with the lack of fall damage? Maybe a parachute in the equipment slot is a better idea? Maybe you could create a new chest slot?
With parachutes you would:
- Have better fall articulation, while being fast enough to avoid being shot (think of how Just Cause feels for reference)
- Have more control over being rag-dolled into submission and killed with a guaranteed on foot landing (assuming you've had enough time to slow down perhaps?).
- Be able to shoot like a f*cking superhero once gliding.
- You could use this also as an opportunity to implement fall damage and really add consequence to choosing to play as a pilot and not bringing one.
You could also do two types, similar to how there are two types of grenade and such - there could be:
- the more dome-like, controlled parachute, for landing below you.
- the more arch-shaped parachute for gliding.(edited)
In addition to these benefits, you could use this opportunity to create a chest slot which is tied to a hotkey, (perhaps [ I ])
Chest Items could include the following:
-Backpack:
Creates fourth equipment slot
- Bomb vest:
Causes player to explode
- Drop Parachute
- Glide Parachute
Chest armor:
- adds 100 extra unreplenishable HP in a seperate bar
I do hope you have a think over my ideas, and excited to see what you do next!
AMAZING WORK!

PS: drop planes with a "Dive" command? ;)

**Comment by Maffnwy** [comment]
#72 #37 #44 
@Modelmat @RubenTheDuck

**Comment by RubenTheDuck** [comment]
Please add every suggestion as a separate issue.

**Comment by Maffnwy** [comment]
Did you at least read it?

**Comment by Maffnwy** [comment]
and they were kind of all connected to one idea.

**Comment by Modelmat** [comment]
At least clearly define each idea as one, this is **NOT** a feedback page.

**Comment by Maffnwy** [comment]
okay. removed compliments. as for the ideas, I have articulated and edited, but I'm not sure how to separate these things into individual concepts as they kind of fall under the same stream of thought - I just think it's a shame you guys have closed this so early and not really given it any thoughts or feedback? @RubenTheDuck  wanted me to post this here?

**Comment by Modelmat** [comment]
https://github.com/RF-Stuff/Bugs-Suggestions/issues/37 This is the first issue, thisi s why this is a duplicate and has been closed. Place your suggestions in there.
